import Sidebar from '@/components/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Sidebar */}
      <Sidebar />
      <body>
        <main>
          {/* Header */}
          {children}
        </main>
      </body>
    </html>
  );
}
